[phases.setup]
nixPkgs = ["python311", "pkg-config"]
aptPkgs = []

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn library_system.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
